#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Set default editor
export EDITOR=/usr/local/bin/vim
export VISUAL=/usr/local/bin/vim

# Customize to your needs...
source ~/.aliases

# Start rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
  
# Add homebrew to the completion path
fpath=("/usr/local/bin/" $fpath)
ulimit -n 10240
 
# Add node path
export NODE_PATH=/usr/local/share/npm/lib/node_modules
